# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
        #Symfony\Component\Security\Core\User\User: bcrypt
        #Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        in_memory:
#            memory:
#                users:
#                    ryan:
#                        password: ryanpass
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: admin
#                        roles: 'ROLE_ADMIN'

    providers:
        database_users:
            entity: { class: AppBundle:User, property: email }
    firewalls:
        main:
            anonymous: ~
#            form_login:
#                login_path: login
#                check_path: login
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_ADMIN }